/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikerental;

/**
 *
 * @author firstx
 */
public class FormMenuMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuMain
     */
    public FormMenuMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelShowTime = new javax.swing.JLabel();
        iconLogo = new javax.swing.JLabel();
        labelShowDate = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        line = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_moter = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuMainMenu = new javax.swing.JMenu();
        menuBikeInfo = new javax.swing.JMenu();
        menuCusInfo = new javax.swing.JMenu();
        menuRentBike = new javax.swing.JMenu();
        menuReturnBike = new javax.swing.JMenu();
        menuIncome = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        head.setBackground(new java.awt.Color(255, 255, 255));
        head.setMinimumSize(new java.awt.Dimension(900, 600));
        head.setPreferredSize(new java.awt.Dimension(902, 600));
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        labelName.setText("RENTAL CARS");
        head.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        labelShowTime.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        labelShowTime.setText("HH:MM:SS A");
        head.add(labelShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/R (1).png"))); // NOI18N
        head.add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        labelShowDate.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        labelShowDate.setText("dd-MM-yyyy");
        head.add(labelShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        head.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 900, -1));

        line.setBackground(new java.awt.Color(238, 88, 40));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        head.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 920, -1));

        txtSearch.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        txtSearch.setToolTipText("");
        txtSearch.setName(""); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        head.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 470, 30));

        btnSearch.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch.setText("ค้นหา");
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        head.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 100, 40));

        btnAll.setBackground(new java.awt.Color(255, 255, 255));
        btnAll.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all.png"))); // NOI18N
        btnAll.setText("ดูทั้งหมด");
        btnAll.setBorderPainted(false);
        btnAll.setContentAreaFilled(false);
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });
        head.add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 120, 40));

        tb_moter.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        tb_moter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_moter);

        head.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 780, 350));

        menuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 0), 1, true));
        menuBar.setEnabled(false);

        menuMainMenu.setBorder(null);
        menuMainMenu.setText("เมนูหลัก");
        menuMainMenu.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMainMenuMouseClicked(evt);
            }
        });
        menuBar.add(menuMainMenu);

        menuBikeInfo.setBorder(null);
        menuBikeInfo.setText("ข้อมูลรถ");
        menuBikeInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuBikeInfo);

        menuCusInfo.setText("ข้อมูลลูกค้า");
        menuCusInfo.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuCusInfo);

        menuRentBike.setBorder(null);
        menuRentBike.setText("การเช่า");
        menuRentBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuRentBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuRentBikeMousePressed(evt);
            }
        });
        menuBar.add(menuRentBike);

        menuReturnBike.setBorder(null);
        menuReturnBike.setText("การคืน");
        menuReturnBike.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuReturnBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuReturnBikeMousePressed(evt);
            }
        });
        menuBar.add(menuReturnBike);

        menuIncome.setBorder(null);
        menuIncome.setText("รายได้");
        menuIncome.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuBar.add(menuIncome);

        menuLogout.setBorder(null);
        menuLogout.setText("ออกจากระบบ");
        menuLogout.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLogoutMousePressed(evt);
            }
        });
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(head, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMainMenuMouseClicked
        
    }//GEN-LAST:event_menuMainMenuMouseClicked

    private void menuRentBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRentBikeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRentBikeMousePressed

    private void menuReturnBikeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReturnBikeMousePressed
       // TODO add your handling code here:
    }//GEN-LAST:event_menuReturnBikeMousePressed

    private void menuLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMousePressed

        // TODO add your handling code here:*/
    }//GEN-LAST:event_menuLogoutMousePressed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel head;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelShowDate;
    private javax.swing.JLabel labelShowTime;
    private javax.swing.JPanel line;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBikeInfo;
    private javax.swing.JMenu menuCusInfo;
    private javax.swing.JMenu menuIncome;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuMainMenu;
    private javax.swing.JMenu menuRentBike;
    private javax.swing.JMenu menuReturnBike;
    private javax.swing.JTable tb_moter;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
